
DROP TYPE IF EXISTS grocery;

CREATE TYPE grocery AS ENUM (
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);
CREATE TABLE IF NOT EXISTS shopping_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT,
  price FLOAT(2),
  date_added TIMESTAMP DEFAULT now() NOT NULL,
  checked BOOL DEFAULT false,
  category grocery NOT NULL
);